### ISSUE TITLE
Comment imports not working fully...

### ISSUE THREAD

**Issue by johnbreslin** [jpSimkins/Drupal2WordPress-Plugin#1]
This should fix it:

      // Fetch comment ID level of comments
        $dComments = $this->_drupalDB->results(
            "SELECT DISTINCT
                c.cid AS comment_ID,
                c.nid AS comment_post_ID,
                c.uid AS user_id,
                c.name AS comment_author,
                c.mail AS comment_author_email,
                c.homepage AS comment_author_url,
                c.hostname AS comment_author_IP,
                f.comment_body_value AS comment_content,
                FROM_UNIXTIME(c.created) AS comment_date
            FROM ".$this->dbSettings['prefix']."comment c, ".$this->dbSettings['prefix']."field_data_comment_body f
            WHERE c.pid = {$commentID}
                AND c.status = 1
                AND c.cid = f.entity_id
            ");

Also change the third %d to a %s for the comment_author name.

**Comment by jpSimkins** [comment]
Thanks for that. It seems I accidentally deleted the join method for the table entirely. I will be pushing the update tonight to solve this issue.

**Comment by jpSimkins** [comment]
This is now fixed in the version 1.4 release. I also added new hooks and removed old code. I also change the way users are imported to solve out of memory issues for larger user base.

**Comment by jpSimkins** [comment]
Missed the `%d` to `%s`. This is now fixed in version 1.4.1 release. Thanks for your input :+1:

**Comment by johnbreslin** [comment]
Thank you! This is a great script, found it very useful. I may have some
more feedback but well done and much appreciated.

On Thursday, March 26, 2015, Jeremy Simkins <notifications@github.com>
wrote:

> Closed #1 <https://github.com/jpSimkins/Drupal2WordPress-Plugin/issues/1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jpSimkins/Drupal2WordPress-Plugin/issues/1#event-266433242>
> .
>


-- 
*John Breslin*
Educator/Engineer/Entrepreneur
http://johnbreslin.com/
@johnbreslin <http://twitter.com/johnbreslin>


* <http://technologyvoice.com/>*
<http://streamglider.com/>
