### ISSUE TITLE
Drupal 5 Support

### ISSUE THREAD

**Issue by pracko** [jpSimkins/Drupal2WordPress-Plugin#11]
Is an import from a Drupal 5 installation possible with this plugin? I tried, but version 7 was the only option allowed within the plugin. I noted in the ReadMe that Drupal versions are "pluggable" but I don't know what that means for me practiacally as an end-user in terms of getting this to work with D5. Thanks in advance.

**Comment by jpSimkins** [comment]
It is pluggable as it can easily be extended to add support for 5, 8, etc. I only added in support for 7 as that is what I needed. The point of having it on github was so others could modify it as needed.
