### ISSUE TITLE
Failed to connect to the Drupal database.

### ISSUE THREAD

**Issue by brody182** [jpSimkins/Drupal2WordPress-Plugin#12]
i am getting an error message "Failed to connect to the Drupal database."

 on my local Dev environment

also cannot connect to external database (blue host) same error message

Database Host : localhost
Database Name : databasename
Database Username : root
Database Password : 

the password is not set so its blank

**Comment by Pecka40** [comment]
Try setting a password. It should work for you then. I had the same problem, added a password and it got further. Now im just waiting on a blank screen, dont really know if something is loading or not.

**Comment by jpSimkins** [comment]
Pushed the fix to the master. Empty DB passwords are now allowed...
