### ISSUE TITLE
Failed to connect to the Drupal database.

### ISSUE THREAD

**Issue by ljr95** [jpSimkins/Drupal2WordPress-Plugin#22]
Hello,
I installed a new version of wordpress (4.6) in localhost , also the BDD Drupal.
But I have this error message "Failed to connect to the Drupal database."

I tried with the database online , but I have the same problem.

Do you have an idea?

thank you very much

**Comment by jpSimkins** [comment]
If your Drupal DB credentials are correct, the most likely issue would be that your user may only have local access to the DB and not remote access(issue with online DB only). You would need to create a user with wildcard access to the DB and use those credentials.

For you local DB, make sure the user has access to the drupal DB on localhost

**Comment by jpSimkins** [comment]
No reply, assuming user-end issue.
