### ISSUE TITLE
Custom Content Type Manager no longer available on Wordpress.org?

### ISSUE THREAD

**Issue by robbielink** [jpSimkins/Drupal2WordPress-Plugin#26]
Can't find the recommended plugin on wordpress.org - link is dead. Is there another recommended plugin? I'm thinking of trying this.

**Comment by jpSimkins** [comment]
That was a plugin I used when I was working on this plugin full-time. Really, you just have to have the custom post types already defined for when you want to import. You can use any plugin to do this or just create them yourself. It doesn't matter which way you go with this. The point is, you just need the custom post types defined when you are going to import. Feel free to use any plugin you want.
