### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by Uhehesh** [jpSimkins/Drupal2WordPress-Plugin#4]
Hello, I'm trying to transfer my content from Drupal to WP, but I receive this error while trying to begin the process:
Failed to connect to the Drupal database.

Here is the log of the MySQL:
> 150426 14:31:11	   18 Connect	root@localhost on 
		   18 Query	SET NAMES utf8
		   18 Query	SELECT @@SESSION.sql_mode
		   18 Init DB	okna
		   18 Query	SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes'
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'theme_mods_twentyfifteen' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'current_theme' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'mods_Twenty Fifteen' LIMIT 1
		   18 Query	SELECT * FROM wp_users WHERE user_login = 'admin'
		   18 Query	SELECT user_id, meta_key, meta_value FROM wp_usermeta WHERE user_id IN (1) ORDER BY umeta_id ASC
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'widget_pages' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'widget_calendar' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'widget_tag_cloud' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'widget_nav_menu' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'theme_switched' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'db_upgraded' LIMIT 1
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'dismissed_update_core' LIMIT 1
		   18 Query	SELECT comment_approved, COUNT( * ) AS num_comments FROM wp_comments  GROUP BY comment_approved
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'auto_core_update_failed' LIMIT 1
		   18 Query	SELECT autoload FROM wp_options WHERE option_name = 'rewrite_rules'
		   18 Query	SELECT option_value FROM wp_options WHERE option_name = 'rewrite_rules' LIMIT 1
		   18 Quit

Do you guys have any ideas what to do? Or is my database config the problem?

**Comment by jpSimkins** [comment]
There really isn't enough to work off on this. This is WordPress queries but nothing looks out of ordinary to me. It appears to be loading basic WordPress information and any theme customization's.

Does your site still work? Does your site work if you delete this plugin? When does the issue appear?

I need something to attempt to duplicate the issue so I can isolate it or to see if it's just on your end.

**Comment by Uhehesh** [comment]
There was some kind of error, AFAIK the script didn't support empty password field. I had to fix it on my own somehow.
