### ISSUE TITLE
Undefined index: options plugins/drupal2wp/inc/Drupal2WordPressDrupalVersionAdapter.php on line 110

### ISSUE THREAD

**Issue by alscheuring** [jpSimkins/Drupal2WordPress-Plugin#5]
Trying this with WP 4.2.1 and I get this error:

undefined index: options in plugins/drupal2wp/inc/Drupal2WordPressDrupalVersionAdapter.php on line 110

**Comment by jpSimkins** [comment]
That is a PHP notice, script should work fine. I assume this is on the first step. It's a simple fix to resolve the notice but it shouldn't prevent it from working. I'll push out an update in the next week or two to resolve this.

**Comment by ryansigg** [comment]
Experiencing the same exact notice, on the first step. 
Leaving prefix field blank.
Drupal and WP are on the same server.

**Comment by jpSimkins** [comment]
Lastest master should have these issues fixed.
