### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by drywall** [jpSimkins/Drupal2WordPress-Plugin#6]
Got a lot of these messages on import: 

`Error querying database. : SELECT u.fid, m.uri, m.filename, m.origname FROM file_usage u LEFT JOIN file_managed m ON (m.fid = u.fid) WHERE u.type = 'node' AND u.id = [XXX]`

My files_managed table doesn't have an 'origname' column.

**Comment by jpSimkins** [comment]
Thanks for the report. I will look into this when I get a chance.

**Comment by drywall** [comment]
NP. This is a thing worth putting energy into. It's awesome.

Resolved a few other minor errors, if I get a chance I'll submit some pull requests.

**Comment by jpSimkins** [comment]
This is now fixed in the master.
