### ISSUE TITLE
Why not use wp_insert_author()?

### ISSUE THREAD

**Issue by drywall** [jpSimkins/Drupal2WordPress-Plugin#8]
Browsing through the source, looks like there are a lot of acrobatics for _importUsersData() inserts. Just curious why wp_insert_author() isn't being used...?

**Comment by jpSimkins** [comment]
Assuming you are referring to `wp_insert_user`, valid question. I am currently in the process of overhauling this plugin and that is used in the new version. When I started on this project I was basing it off a SQL script and for lack of better judgement I created the `_importUsersData` method. 

Originally, this was a small script for personal use. I then decided to clean it up and release it. Shortly afterwards I realized that I should re-structure the entire plugin to be more scalable and integrate proper core WordPress features.

Not sure when I will have the new code available as it is a complete rewrite but moving forward, I am using core WordPress methods.

**Comment by drywall** [comment]
Cool. I'm happy to help out in what little spare time I have available.
